# Generated by Django 5.1.4 on 2024-12-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_user_authentication', '0002_alter_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.URLField(max_length=150, null=True),
        ),
    ]
